### ISSUE TITLE
Unknown response received from server

### ISSUE THREAD

**Issue by jydy** [Noitidart/Songifier#1]
Songifier was working perfectly. Suddenly started returning with "Unknown response received from server" (after fairly intensive use)

Tried a few basic things: Internet connection is OK. Tried re-installing the addon. Rebooted my PC. No luck.

**Comment by Noitidart** [comment]
Thank you so much Jim for being a user! I will check with the ACRCloud folks, they allowed me to use their service for free, they might have changed their mind. I will definitely update you.

**Comment by jydy** [comment]
The problem seems to have gone now. I have been using the addon most of the day without problems.
I would still be interested to know what happened if possible.

Many thanks.

**Comment by Noitidart** [comment]
Thanks for that update! I will definitely look into this to see whats up and post an update :)
